### ISSUE TITLE
Thesis location

### ISSUE THREAD

**Issue by mictadlo** [michelleteranp/msc-thesis-michelle-teran-2022#2]
Hi,
Could you share your thesis with me? I am interested to read it.

Thank you in advance,

Best wishes,

Michal

**Comment by michelleteranp** [comment]
Hi Michal,

Thanks for your interest in my thesis.
Here it is:
[Teran_Michelle_ 17600693.pdf](https://github.com/michelleteranp/msc-thesis-michelle-teran-2022/files/11059570/Teran_Michelle_.17600693.pdf)

Regards,
Michelle
